---
- name: check platform
  fail:
    msg: "Distro {{ ansible_distribution }} not supported"
  when: ansible_os_family not in ['Debian', 'RedHat']

- name: get the platform specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages
  package:
    name: "{{ perl_packages }}"
    state: present

- name: get the cpan script
  get_url:
    url: "{{ perl_cpanm_url }}"
    dest: "{{ perl_cpanm_path }}"
    owner: root
    group: root
    mode: 0755
